# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [4]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(arr)

arr[:,2]=1
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  1  4  5]
 [ 6  7  1  9 10]
 [11 12  1 14 15]
 [16 17  1 19 20]]


In [8]:
import numpy as np
array=np.arange(1,17).reshape(4,4)
print(array)

np.fill_diagonal(array,0)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [12]:
import numpy as np
array=np.arange(1,37).reshape((6,6))
print(array)

subarray=array[2:5,1:4]
print(subarray)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [16]:
array=np.arange(1,17).reshape(4,4)
rowsum=np.sum(array,axis=1)
colsum=np.sum(array,axis=0)
print(rowsum)
print(colsum)


[10 26 42 58]
[28 32 36 40]


In [19]:
import numpy as np
array=np.random.randint(1,21,size=(5,5))
print(array)
mean=np.mean(array)
variance=np.var(array)
median=np.median(array)
Standarad_deviation=np.std(array)
print(mean)
print(variance)
print(median)
print(Standarad_deviation)

[[17 10 12 20 15]
 [ 9 20  5 17 16]
 [13  6  1 15 20]
 [ 2  2  4 18 20]
 [ 2  6  4 20 16]]
11.6
45.43999999999999
13.0
6.740919818541086


In [20]:
array=np.arange(1,10).reshape(3,3)
mean=np.mean(array)
stddev=np.std(array)
normalized_data=(array-mean)/stddev
print(stddev)


2.581988897471611


In [21]:
array=np.random.randint(1,11,size=(3,3))
rowarray=np.random.randint(1,11,size=(3,))
result=array+rowarray
print(result)


[[13 15 16]
 [ 9 17 12]
 [15 12 15]]


In [24]:
array=np.random.randint(1,11,size=(4,4))
colarr=np.random.randint(1,11,size=(4,))

result=array-colarr[:,np.newaxis]
print(result)

[[ 5  1  3  8]
 [ 5  3 -4  2]
 [ 1 -3  3  3]
 [ 1  0  1  2]]


In [26]:
matrix=np.random.randint(1,11,size=(3,3))
print(matrix)
determinant=np.linalg.det(matrix)
print(determinant)
inverse=np.linalg.inv(matrix)
print(inverse)
Eigenval=np.linalg.eigvals(matrix)
print(Eigenval)

[[ 8  3 10]
 [ 1 10  9]
 [ 8  7  7]]
-479.0000000000003
[[-0.01461378 -0.10229645  0.15240084]
 [-0.13569937  0.05010438  0.12943633]
 [ 0.15240084  0.06680585 -0.16075157]]
[21.07444147  7.11849997 -3.19294143]


In [27]:
arr1=np.random.randint(1,11,size=(2,3))
arr2=np.random.randint(1,11,size=(3,2))
result=np.dot(arr1,arr2)
print(result)

[[154 151]
 [109 121]]


In [28]:
arr=np.arange(1,10).reshape((3,3))
arr.reshape(1,9)
print(arr)
arr.reshape(9,1)
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr=np.arange(1,10).reshape((3,3))
newarr=arr.flatten()
print(newarr)
sfs=newarr.reshape((5,5))
print(newarr)

[1 2 3 4 5 6 7 8 9]


ValueError: cannot reshape array of size 9 into shape (5,5)

In [33]:
array=np.random.randint(1,21,size=(4,4))
array[array>10]=10
print(array)

[[10 10 10  1]
 [10 10 10 10]
 [ 9 10 10 10]
 [10 10  7 10]]


In [ ]:
data_type=[('x','i4'),('y','i4')]
data=np.array([(1,2),(3,4),(5,6)],dtype=data_type)
print(data)

